export type Language = 'pt' | 'en';

export const WHATSAPP_NUMBER = '351911923499';
export const WHATSAPP_LINK = `https://wa.me/${WHATSAPP_NUMBER}`;
export const EMAIL = 'administrativo@northscapetours.pt';

export const CONTENT = {
    pt: {
        nav: {
            home: 'Início', tourDouro: 'Tour no Douro', douroADois: 'Douro a Dois',
            transfer: 'Transfer', about: 'Sobre Nós', reviews: 'Avaliações',
            blog: 'Blog', contact: 'Contacto', book: 'Reservar', bookNow: 'Reservar Agora',
        },
        hero: {
            subtitle: 'Experiências Exclusivas no Norte de Portugal',
            title1: 'Experiências exclusivas no Douro',
            title2: 'com degustação de vinhos e passeio de barco.',
            desc: 'Saídas do Porto com transfer confortável e atendimento personalizado.',
            cta: 'Ver Experiências',
            ctaWhatsapp: 'Falar via WhatsApp',
            trustLine: 'Serviço licenciado · Cancelamento gratuito até 48h · Guias bilíngues',
        },
        quote: {
            text1: '"O Douro não é uma paisagem,',
            text2: 'é um poema geológico."',
            author: 'Miguel Torga',
        },
        tourDouro: {
            badge: 'Mais Reservado',
            title: 'Tour no Douro — Experiência Completa',
            subtitle: 'Prova de Vinhos, Almoço Regional e Passeio de Barco',
            intro: 'Descubra o coração do Vale do Douro, Património Mundial da UNESCO. Explore uma das regiões vinícolas mais antigas do mundo numa experiência cuidadosamente planeada para proporcionar conforto, autenticidade e momentos memoráveis.',
            timelineTitle: 'O Seu Dia, Hora a Hora',
            timeline: [
                { time: '08:30', title: 'Recolha no Porto', desc: 'A experiência começa com recolha no Porto. Durante o percurso até ao Douro, o guia partilha informações sobre a história da região.' },
                { time: '10:00', title: 'Chegada ao Douro Vinhateiro', desc: 'Primeiras paragens panorâmicas nos socalcos. Fotografias em miradouros icónicos com vista para o rio e as vinhas.' },
                { time: '10:30', title: 'Visita a Vinícola Selecionada', desc: 'Visita guiada a quinta produtora tradicional. Prova de vinhos DOC Douro e Porto.' },
                { time: '12:30', title: 'Almoço Regional', desc: 'Almoço tradicional em restaurante selecionado, com pratos típicos da região e harmonização com vinhos locais.' },
                { time: '14:30', title: 'Passeio de Barco no Rio Douro', desc: 'Passeio de barco tradicional pelo rio Douro. Paisagens cinematográficas em socalcos.' },
                { time: '16:00', title: 'Regresso ao Porto', desc: 'Ao final da tarde, regressamos ao Porto com total comodidade.' },
            ],
            includedTitle: 'O Que Está Incluído',
            included: [
                'Transfer ida e volta desde o Porto',
                'Visita a vinícola selecionada',
                'Prova de vinhos DOC Douro',
                'Almoço tradicional com vinhos locais',
                'Passeio de barco tradicional no rio Douro',
                'Guia acompanhante bilíngue (Português e Inglês)',
            ],
            groupNote: 'Experiência pensada para pequenos grupos, garantindo atenção personalizada.',
            detailsTitle: 'Informações Práticas',
            duration: '8 a 9 horas (dia completo)',
            departure: 'Entre 8h00 e 9h00 (confirmação na reserva)',
            groupType: 'Privado ou partilhado (mediante disponibilidade)',
            languages: 'Português e Inglês',
            cancellation: 'Cancelamento gratuito até 48 horas antes do tour',
            forWhomTitle: 'Ideal Para',
            forWhom: ['Casais', 'Grupos de amigos', 'Famílias', 'Visitantes internacionais', 'Amantes de vinho'],
            price: '89',
            priceLabel: 'A partir de',
            priceUnit: '€/pessoa',
            priceIncludes: 'Transporte + Vinícola + Vinhos + Barco + Almoço',
            ctaBook: 'Reserve a Sua Experiência',
            ctaWhatsapp: 'Perguntas? Fale Connosco',
        },
        douroADois: {
            badge: 'Exclusivo para Casais',
            title: 'Douro a Dois — Experiência Romântica Exclusiva',
            subtitle: 'Um Dia Criado Apenas para Dois no Vale do Douro',
            intro: 'No cenário intemporal do Vale do Douro, esta experiência foi desenhada para casais que procuram exclusividade, privacidade e momentos verdadeiramente memoráveis. Cada etapa é pensada como parte de uma narrativa romântica.',
            noGroup: 'Sem grupos. Sem pressa. Sem distrações. Apenas vocês dois e o Douro como cenário.',
            timelineTitle: 'A Experiência',
            timeline: [
                { time: '09:00', title: 'Recolha Privada no Porto', desc: 'Viagem em viatura executiva premium. Início de um dia pensado ao detalhe.' },
                { time: '10:30', title: 'Miradouros Panorâmicos', desc: 'Paragens estratégicas nos pontos mais fotogénicos do Douro.' },
                { time: '11:00', title: 'Vinícola Privada com Prova Premium', desc: 'Visita privada a vinícola selecionada com prova de vinhos de excelência.' },
                { time: '13:00', title: 'Almoço em Restaurante Michelin', desc: 'Mesa reservada em restaurante distinguido pelo Guia Michelin.' },
                { time: '15:00', title: 'Passeio de Barco Privado', desc: 'Passeio de barco preparado com decoração especial para o casal.' },
                { time: '17:00', title: 'Regresso ao Porto', desc: 'Viagem tranquila de regresso, com memórias para toda a vida.' },
            ],
            boatTitle: 'O Momento no Rio – Barco Decorado',
            boatDesc: 'O passeio de barco não é apenas um trajeto. O espaço é preparado com decoração especial para o casal, criando um ambiente íntimo e sofisticado. Um cenário perfeito para pedidos de casamento, aniversários de casamento, lua de mel ou datas marcantes.',
            photoTitle: 'Serviço Opcional – Fotógrafo Profissional',
            photoDesc: 'Para quem deseja eternizar o momento, disponibilizamos um fotógrafo especializado em casais. Inclui registo discreto, sessão em cenários icónicos, seleção com edição profissional e entrega digital em alta resolução. (Disponível como upgrade adicional).',
            includedTitle: 'O Que Está Incluído',
            included: [
                'Transporte privado executivo (ida e volta)',
                'Planeamento personalizado da experiência',
                'Reserva em restaurante Michelin',
                'Visita e prova premium em vinícola',
                'Passeio de barco privado com decoração especial',
                'Assistência personalizada (Português/Inglês)',
            ],
            price: '490',
            priceLabel: 'A partir de',
            priceUnit: '€/casal',
            photoUpgrade: 'Serviço de fotógrafo disponível como opção adicional.',
            bookingNote: 'Reserva antecipada recomendada. A experiência é realizada mediante confirmação de disponibilidade do restaurante e barco privado.',
            ctaBook: 'Solicitar Disponibilidade',
            ctaWhatsapp: 'Planear Experiência',
        },
        transfer: {
            badge: 'Serviço Premium',
            title: 'Transfer Executivo no Porto',
            subtitle: 'Conforto, Pontualidade e Excelência em Cada Detalhe',
            intro: 'Oferecemos serviço de transfer executivo privado no Porto, com recolha e entrega no hotel, residência ou no Aeroporto Francisco Sá Carneiro. Um serviço pensado para viajantes exigentes.',
            features: [
                { title: 'Pontualidade e Planeamento Premium', items: ['O seu tempo é valioso.', 'Monitorização de voo em tempo real', 'Motorista no local antes do horário', 'Tempo de espera incluído na chegada'] },
                { title: 'Viatura Exectiva até 8 Passageiros', items: ['Interior confortável, silencioso e espaçoso', 'Amplo espaço para bagagem', 'Ar condicionado', 'Ideal para famílias ou executivos'] },
                { title: 'Segurança e Excelência', items: ['Motoristas experientes e bilíngues', 'Cadeirinha de bebé (mediante pedido)', 'Serviço totalmente licenciado e seguro'] },
            ],
            services: [
                { title: 'Transfer Aeroporto → Hotel', desc: 'Acompanhamento do voo, receção na área de chegadas, assistência total com a bagagem e transporte direto ao seu destino.' },
                { title: 'Transfer Hotel → Aeroporto', desc: 'Recolha pontual no hotel ou alojamento com planeamento adequado para garantir a chegada atempada ao aeroporto.' },
            ],
            price: '45',
            priceLabel: 'A partir de',
            priceUnit: '€/transfer',
            ctaBook: 'Solicitar Cotação Personalizada',
            ctaWhatsapp: 'Reservar via WhatsApp',
        },
        about: {
            badge: 'Quem Somos',
            title: 'Experiências Autênticas no Norte de Portugal',
            mission: 'Na North Scape Tours, o cliente não é um turista. É um convidado especial.',
            pillars: [
                { title: 'O Douro que se vive', desc: 'Os nossos roteiros vão além do óbvio. Conectamos cada cliente a vinícolas selecionadas, provas enogastronómicas autênticas e paisagens de tirar o fôlego.' },
                { title: 'O nosso diferencial', desc: 'Atendimento próximo, humano e personalizado. Roteiros feitos à medida e uma curadoria rigorosa de parceiros locais de excelência em conforto e segurança.' },
                { title: 'Muito além do Douro', desc: 'Exploramos o património histórico, a gastronomia e a natureza fora do turismo massificado, sempre com um padrão elevado de serviço.' },
            ],
            promise: 'A nossa promessa é criar experiências memoráveis, onde cada paisagem, cada vinho e cada momento se transformam numa ligação real com Portugal.',
            teamTitle: 'A Equipa',
            teamDesc: 'A nossa equipa é composta por profissionais apaixonados pelo Douro e pela hospitalidade portuguesa, sempre prontos para receber visitantes de todo o mundo. Estamos prontos para organizar a sua experiência.',
        },
        reviews: {
            badge: 'Avaliações',
            title: 'O Que Dizem os Nossos Clientes',
            subtitle: 'Cada review é uma história real de quem viveu a experiência.',
            rating: '4.9', totalReviews: '127',
            items: [
                { text: 'Uma experiência que transcende o turismo. Sentimo-nos como convidados de honra numa das regiões mais belas do mundo. O guia foi excepcional e a atenção ao detalhe impressionante.', author: 'Sofia Albuquerque', location: 'Lisboa, Portugal', flag: '🇵🇹', stars: 5 },
                { text: 'The attention to detail was impeccable. From the private boat ride to the exclusive wine tastings, everything was perfect. Highly recommended for anyone visiting Porto.', author: 'James Sterling', location: 'London, UK', flag: '🇬🇧', stars: 5 },
                { text: 'Une journée magique dans la vallée du Douro. Le guide était exceptionnel, les vins superbes et le déjeuner absolument délicieux. À refaire absolument!', author: 'Marie Dubois', location: 'Paris, France', flag: '🇫🇷', stars: 4.5 },
                { text: 'Melhor experiência de sempre no Douro! O passeio de barco ao pôr do sol foi inesquecível. Recomendo muito a North Scape Tours.', author: 'Carlos Mendes', location: 'São Paulo, Brasil', flag: '🇧🇷', stars: 5 },
                { text: 'Ein perfekter Tag im Douro-Tal! Die Weinprobe war erstklassig und die Landschaft atemberaubend. Wir kommen auf jeden Fall wieder.', author: 'Hannah Müller', location: 'Munique, Alemanha', flag: '🇩🇪', stars: 4.8 },
                { text: 'We celebrated our anniversary with North Scape and it was the highlight of our trip. The private experience felt truly exclusive. Worth every penny.', author: 'Michael & Sarah Chen', location: 'New York, EUA', flag: '🇺🇸', stars: 5 },
                { text: 'La guida sapeva tutto sui vini e sulla storia della regione. Un viaggio indimenticabile che consiglio a tutti gli amanti del vino.', author: 'Alessandro Rossi', location: 'Milão, Itália', flag: '🇮🇹', stars: 4.5 },
                { text: 'El transfer desde el aeropuerto fue impecable, y el tour al día siguiente superó todas nuestras expectativas. Servicio de primera clase.', author: 'Lucía Fernández', location: 'Madrid, Espanha', flag: '🇪🇸', stars: 5 },
                { text: 'Geweldige ervaring! De boot op de Douro bij zonsondergang was magisch. Professionele service van begin tot eind.', author: 'Daan van der Berg', location: 'Amesterdão, Holanda', flag: '🇳🇱', stars: 4.8 },
            ],
        },
        faq: {
            badge: 'Perguntas Frequentes',
            title: 'Tudo o Que Precisa de Saber',
            items: [
                { q: 'O que está incluído no Tour ao Douro?', a: 'O tour inclui transfer ida e volta desde o Porto, visita a vinícola selecionada, prova de vinhos DOC Douro, almoço em restaurante regional e passeio de barco pelo rio Douro. Guia bilíngue (PT/EN) incluído.' },
                { q: 'Quanto tempo dura a experiência?', a: 'O Tour no Douro tem duração de 8 a 9 horas (dia completo). A experiência Douro a Dois também tem a mesma duração.' },
                { q: 'É adequado para famílias com crianças?', a: 'Sim! O Tour no Douro é ideal para famílias. As crianças são bem-vindas e temos cadeirinha de bebé disponível para o transfer. Há opções de menu infantil nos restaurantes.' },
                { q: 'Posso personalizar a experiência?', a: 'Absolutamente. Oferecemos tours privados onde pode adaptar o roteiro, escolher vinícolas específicas ou adicionar paragens. Contacte-nos para um tour à medida.' },
                { q: 'Qual a política de cancelamento?', a: 'Cancelamento gratuito até 48 horas antes da data do tour. Após este prazo, aplica-se a tarifa completa.' },
                { q: 'Existem opções vegetarianas ou restrições alimentares?', a: 'Sim. Os nossos restaurantes parceiros oferecem opções vegetarianas, veganas e adaptadas a alergias. Informe-nos no momento da reserva.' },
                { q: 'Os tours funcionam durante todo o ano?', a: 'Sim, os tours operam durante todo o ano. Cada estação oferece uma paisagem diferente: vinhas verdes na primavera, colheita no outono e socalcos dourados no inverno.' },
                { q: 'Como funciona o transfer executivo?', a: 'O motorista chega ao local antes do horário combinado. Para transfers de aeroporto, monitorizamos o voo em tempo real. Viatura executiva com capacidade até 8 passageiros.' },
                { q: 'Em que idiomas é feito o tour?', a: 'Os nossos guias são fluentes em Português e Inglês. Para outros idiomas, consulte-nos para verificar disponibilidade.' },
                { q: 'Como posso reservar?', a: 'Pode reservar diretamente pelo nosso website, por WhatsApp ou por email. Confirmamos a sua reserva em menos de 2 horas.' },
            ],
        },
        blog: {
            badge: 'Blog',
            title: 'Histórias do Douro',
            subtitle: 'Dicas, roteiros e inspiração para a sua viagem.',
            readMore: 'Ler Artigo',
            items: [
                {
                    slug: 'miradouros-douro', title: 'Os 5 Miradouros Mais Instagramáveis do Douro Vinhateiro', excerpt: 'De São Leonardo de Galafura ao Miradouro do Imaginário — os pontos de vista que transformam qualquer foto numa obra-prima. Descubra os segredos mais bem guardados da região.', date: '18 Fev 2026', category: 'Miradouros', image: '/images/blog/douro_viewpoint_1771611805242.png', readTime: '5 min',
                    fullContent: [
                        { type: 'p', text: 'O Vale do Douro não se descreve, vive-se. É um daqueles raros lugares na Terra onde a intervenção humana — os imponentes socalcos de xisto rasgados à mão ao longo de séculos — não destruiu a natureza, mas antes a elevou a uma obra de arte sublime. Contudo, para capturar a verdadeira essência desta região Património Mundial, não basta estar cá. É preciso saber para onde olhar.' },
                        { type: 'p', text: 'Prepare a câmara, limpe a lente e acompanhe-nos nesta viagem pelos 5 miradouros mais espetaculares, dramáticos e perfeitamente fotogénicos da região de Viseu e Vila Real. Estas não são apenas paragens; são convites ao deslumbramento.' },
                        { type: 'h3', text: '1. Miradouro de São Leonardo da Galafura' },
                        { type: 'p', text: 'Aos 640 metros de altitude, o ar é mais rarefeito, mas a recompensa tira-lhe a restante respiração. Miguel Torga, o ilustre poeta português, imortalizou este local chamando-lhe um "excesso de natureza". Ao raiar do sol, o manto de nevoeiro sobre o rio cria um cenário quase místico; ao fim da tarde, o vale incendeia-se num dourado etéreo.' },
                        { type: 'image', url: '/images/blog/douro_viewpoint_1771611805242.png', text: 'A vista deslumbrante a partir de São Leonardo da Galafura. Dica de pro: traga uma objetiva grande angular a partir das 17h para capturar o espetáculo dourado nas vinhas.' },
                        { type: 'p', text: '📍 Coordenadas: 41.1738° N, 7.6710° W. \n💡 Dica Mágica: Leve consigo um cálice do seu Tawny favorito e faça um brinde silencioso à magnitude do rio.' },
                        { type: 'h3', text: '2. Miradouro do Casal de Loivos' },
                        { type: 'p', text: 'A BBC nomeou-o como dono de uma das seis melhores vistas do mundo, e por boas razões. É daqui que o Douro ganha a sua famosa curva perfeita em forma de cotovelo, logo a seguir à vila do Pinhão. É a imagem que estampa os postais mais bonitos de Portugal e as revistas internacionais de turismo de luxo.' },
                        { type: 'blockquote', text: 'No Casal de Loivos, apercebemo-nos da pequenez humana face à persistência milenar de um rio que desenhou o seu próprio destino.' },
                        { type: 'h3', text: '3. Miradouro do Imaginário (Tabuaço)' },
                        { type: 'p', text: 'Enquanto a maioria dos autocarros turísticos se aglomera na margem norte, a margem sul esconde este segredo cintilante. Oferece uma vista dramática, limpa e quase palpável sobre as vinhas em escadaria. Se procura a fotografia "limpa", sem distrações e sem ter de pedir a desconhecidos que saiam do enquadramento, este é o seu refúgio.' },
                        { type: 'h3', text: '4. Miradouro de São Salvador do Mundo' },
                        { type: 'p', text: 'No concelho de São João da Pesqueira, este complexo de capelas brancas contrasta gloriosamente com a crueza da paisagem de escarpas rochosas que estrangulam o rio. A altura vertiginosa permite enquadrar o rio bem lá no fundo, serpenteando por desfiladeiros selvagens que lembram a gênese intocada da região.' },
                        { type: 'h3', text: 'O Segredo dos Nossos Guias' },
                        { type: 'p', text: 'Descobrir estes pontos no seu próprio carro implica conduzir em estradas sinuosas, muito inclinadas e, muitas vezes, desconcertantes para quem não conhece a geografia singular da região. Ao reservar uma experiência privada com a North Scape Tours, os nossos motoristas especializados não só garantem uma viagem segura num veículo premium, como também conhecem a curva exata e a hora perfeita de luz para estacionar e deixá-lo capturar a fotografia da sua vida.' }
                    ]
                },
                {
                    slug: 'vinhos-douro-antigo-novo', title: 'Douro Antigo vs. Douro Novo: O Guia dos Vinhos Que Precisa Provar', excerpt: 'Do imponente Porto Vintage à nova geração dos aclamados vinhos brancos e tintos tranquilos. Descubra a evolução que colocou o Douro no mapa da alta gastronomia.', date: '12 Fev 2026', category: 'Vinhos', image: '/images/blog/douro_wine_1771611833006.png', readTime: '6 min',
                    fullContent: [
                        { type: 'p', text: 'Durante mais de trezentos anos, o nome "Douro" foi inequivocamente sinónimo de um único néctar: o imponente, doce e fortificado Vinho do Porto. Servido nos salões majestosos de Londres, nas caves poeirentas dos bispos antigos e nos brindes comemorativos das realezas, o Porto ditava as regras.' },
                        { type: 'p', text: 'Hoje, contudo, a região depara-se com uma dualidade arrebatadora. Lado a lado com os clássicos Tawnies e Vintages seculares descansam agora vinhos de mesa (DOC Douro) que competem lado a lado com os gigantes de Bordéus e da Borgonha. Mas o que significa isto, na prática, para o seu palato?' },
                        { type: 'h3', text: 'O Ritual Intemporal do Porto' },
                        { type: 'p', text: 'A tradição ainda lidera majestosamente nas grandes e silenciosas Quintas. O método do Douro clássico recusa-se a render-se às máquinas onde os humanos provam ser insubstituíveis: a pisa a pé.' },
                        { type: 'image', url: '/images/blog/douro_wine_1771611833006.png', text: 'A pisa em lagar de granito não é atração turística; é ciência artesanal. O pé humano extrai cor e sabor sem esmagar o caroço da uva, impedindo a amargura.' },
                        { type: 'p', text: 'Num Vintage — a realeza dos Portos —, as uvas são criteriosamente escolhidas, maceração curta e estagiadas em garrafa durante décadas. Um Porto Vintage de ano excecional não é apenas vinho; é uma cápsula do tempo, escura, densa, exuberante em notas de ameixa preta, chocolate e especiarias selvagens.' },
                        { type: 'h3', text: 'A Revolução DOC Douro: O "Novo Douro"' },
                        { type: 'p', text: 'Se o passado foi fortificado, o presente é surpreendentemente elegante. No final dos anos 90, um grupo de produtores visionários (frequentemente chamados de "Douro Boys") começou a mostrar ao mundo que, se parássemos a fortificação precoce, o terroir quente e ríspido de xisto gerava vinhos brancos minerais, cortantes e profundamente gastronómicos, e tintos de enorme complexidade e frescura.' },
                        { type: 'blockquote', text: 'O paradoxo fascinante do Douro moderno é como terras tão duras produzem vinhos tão invulgarmente elegantes. É o triunfo da vinha sobre a pedra.' },
                        { type: 'h3', text: 'Um Guia Rápido de Degustação' },
                        { type: 'p', text: 'Quando se sentar à mesa de uma Quinta connosco, procure detetar os traços das 5 grandes castas autóctones do Douro:' },
                        { type: 'p', text: '🍷 **Touriga Nacional:** O perfume sublime. Procure aromas inconfundíveis a violetas, bergamota (como o chá Earl Grey) e amoras.' },
                        { type: 'p', text: '🍷 **Touriga Franca:** A estrutura, que traz corpo aromático floral leve, mas garante que o vinho perdure na boca.' },
                        { type: 'p', text: '🍷 **Tinta Roriz:** Conhecida mundialmente como Tempranillo, traz a pimenta, a esteva e os frutos encarnados crocantes.' },
                        { type: 'p', text: 'Nas nossas experiências exclusivas de degustação, reservamos-lhe não só as provas, mas reuniões em espaços privados ou até provas diretas de barricas em quintas que recusam convidados comuns. Uma viagem enológica para a vida.' }
                    ]
                },
                {
                    slug: '3-dias-douro-comboio', title: '3 Dias no Douro Sem Carro: Roteiro Completo de Comboio', excerpt: 'Esqueça as preocupações com estacionamento e taxas de álcool. A viagem de comboio Porto–Pinhão é das mais belas travessias férreas da Europa.', date: '6 Fev 2026', category: 'Roteiros', image: '/images/blog/douro_train_1771611847706.png', readTime: '5 min',
                    fullContent: [
                        { type: 'p', text: 'Imagine entrar num comboio no agitado centro do Porto e, uma hora depois, ver pela janela a água do rio quase a tocar nas carruagens. A linha férrea do Douro abraça as escarpas do rio com uma intimidade formidável. Durante grande parte do caminho, não há estrada a acompanhar: apenas o comboio, a água espelhada e, ao fundo, as escadarias verdes que sobem até aos céus.' },
                        { type: 'p', text: 'Se o objetivo é afastar o stress e focar-se em prova de vinhos de qualidade superior sem o receio da condução, elaborar a sua viagem 100% de comboio é a melhor decisão turística que pode tomar.' },
                        { type: 'h3', text: 'Dia 1: Chegada Imersiva ao Pinhão' },
                        { type: 'p', text: 'Apanhe o comboio matinal na deslumbrante estação de São Bento no Porto. Aconselhamos sentar-se sempre do LADO DIREITO (no sentido Porto-Régua-Pinhão) para garantir as vistas do rio em primeira fila. A chegada à estação do Pinhão é digna de um postal: está decorada com mais de vinte e quatro painéis de azulejos ilustrando as épocas douradas das colheitas.' },
                        { type: 'image', url: '/images/blog/douro_train_1771611847706.png', text: 'Estação de comboios do Pinhão: as paredes contam a história das famosas viagens em barco rabelo até ao Porto.' },
                        { type: 'h3', text: 'Dia 2: Acessibilidade a Pé (Barco e Vinhos)' },
                        { type: 'p', text: 'Pinhão concentra uma imensa riqueza num raio de dois quilómetros. De manhã, aproveite o pitoresco cais fluvial para embarcar num cruzeiro vintage. O rio oferece total calmaria e silêncio. À tarde, saiba que não precisa de carro para visitar nomes sonantes: Quintas de renome como a Quinta das Carvalhas ou a Quinta do Bomfim estão a cinco ou dez minutos a pé do centro da vila.' },
                        { type: 'h3', text: 'Dia 3: A Opção de Luxo Flexível' },
                        { type: 'p', text: 'Um plano apenas de comboio tem uma falha: limite à altitude. As quintas mais altas e remotas e os grandes miradouros estão irremediavelmente fora do raio pedestre. É aqui que entra o segredo das viagens de luxo.' },
                        { type: 'blockquote', text: 'A experiência derradeira é apanhar o comboio apenas pelo encanto visual cénico, e ter um motorista particular aguardar a sua chegada nas estações.' },
                        { type: 'p', text: 'Para clientes North Scape Tours, coordenamos a nossa Viatura Premium para que o casal faça os trajetos bonitos de comboio e seja recolhido diretamente na estação do Pinhão pelo seu motorista/guia. Conduzimos pela montanha até ao restaurante estrelado e às provas privadas de altitude que de outra forma perderiam, antes de os reconduzir de volta à estação ao pôr-do-sol. Combinação absoluta do pitoresco com o supremo luxo.' }
                    ]
                },
                {
                    slug: 'vindima-douro-experiencia', title: 'A Magia da Vindima: A Experiência Sensorial Que Muda a Alma', excerpt: 'Pisar uvas em lagares seculares de pedra ao som de cânticos rítmicos. O outono no Douro é uma comunhão visceral entre o homem, a pedra e o sol.', date: '30 Jan 2026', category: 'Experiências', image: '/images/blog/douro_harvest_1771611862889.png', readTime: '5 min',
                    fullContent: [
                        { type: 'p', text: 'Esqueça os tapetes vermelhos; o verdadeiro privilégio europeu caminha-se descalço, com mosto de uva púrpura até ao meio do tornozelo, num lagar de pedra granítica num vale íngreme de Portugal. Setembro e Outubro transformam o calmo vale num frenesim orgânico contagiante; é a altura em que a região reivindica toda uma herança secular e se cumpre o objetivo de um ano inteiro de dedicação intensa.' },
                        { type: 'h3', text: 'A Coreografia do Lagar (Corte e Pisa)' },
                        { type: 'p', text: 'A experiência nas quintas em alturas de vindima permite ir muito além da tradicional fotografia em passeio turístico. Depois de partilhar o almoço e as lides matinais nas encostas acentuadas (cortando cachos grossos das seculares videiras em plataformas suspensas sob a linha do sol), chega o crepúsculo. O foco muda.' },
                        { type: 'image', url: '/images/blog/douro_harvest_1771611862889.png', text: 'A inclinação vertiginosa das vinhas e a proximidade do rio demonstram perfeitamente o título de "viticultura heróica".' },
                        { type: 'p', text: 'Lavam-se atenciosamente as pernas, arregaçam-se calças. Homens e mulheres formam linha braço a braço no interior dos seculares reservatórios de pedra — o lagar. Começa então uma cadência sincronizada "Um... Dois... Esquerda... Direita...".' },
                        { type: 'p', text: 'Este movimento — outrora exaustivo e monótono para os antepassados que lá passavam noites e madrugadas adentro — garante que o mosto da uva é esmagado extraindo sabor e cor intensificados da pele, sem esmagar as delicadas grainhas cujo travo estragaria lotes raros.' },
                        { type: 'blockquote', text: 'Mergulhar num lagar de pedra do Douro sob um céu estrelado é absorver os cheiros potentes da fruta triturada e o calor vibrante humano — não há spa no mundo com a energia desta tradição.' },
                        { type: 'h3', text: 'Planeamento Estratégico para 2026' },
                        { type: 'p', text: 'Participar numa verdadeira vindima não tem ticket comprável num guichet. As vagas nas melhores quintas esgotam com seis a oito meses de antecedência. Na North Scape Tours, conseguimos o impossível pela nossa profunda e enraizada rede de contactos regionais: abrimos portas nas quintas reservadas apenas a hóspedes exclusivos.' },
                        { type: 'p', text: 'Deixe-nos ser os coreógrafos da sua imersão. Preparámos jornadas de vindima para quem procura luxo e essência crua no meio termo perfeito. Fale com o planeamento da agenda de setembro — valerá mais que oiro.' }
                    ]
                }
            ],
        },
        contact: {
            title: 'Pronto para embarcar?',
            desc: 'Deixe-nos desenhar a sua viagem de sonho. Respondemos em menos de 2 horas.',
            ctaBook: 'Reservar Experiência',
            ctaWhatsapp: 'Falar via WhatsApp',
            emailLabel: 'Email', email: EMAIL,
            phoneLabel: 'Telefone', phone: '+351 911 923 499',
        },
        footer: {
            rights: 'Todos os direitos reservados.',
            terms: 'Termos e Condições', privacy: 'Política de Privacidade',
            licensedIn: 'Serviço licenciado em Portugal · RNAVT n.º 11959',
            nif: 'NIF: 247 114 430',
            complaints: 'Livro de Reclamações Eletrónico'
        },
        cookieBanner: {
            text: 'Utilizamos cookies para lhe proporcionar a melhor experiência possível. Ao continuar, consideramos que concorda com a nossa',
            linkText: 'Política de Privacidade',
            acceptBtn: 'Aceitar Todos',
            essentialBtn: 'Apenas Essenciais',
        },
        mobileBar: { book: 'Reservar', whatsapp: 'WhatsApp' },
    },
    en: {
        nav: {
            home: 'Home', tourDouro: 'Douro Tour', douroADois: 'Romantic Escape',
            transfer: 'Transfer', about: 'About', reviews: 'Reviews',
            blog: 'Blog', contact: 'Contact', book: 'Book', bookNow: 'Book Now',
        },
        hero: {
            subtitle: 'Exclusive Experiences in Northern Portugal',
            title1: 'Exclusive Douro experiences',
            title2: 'with wine tasting and river cruise.',
            desc: 'Departures from Porto with comfortable transfer and personalised service.',
            cta: 'View Experiences',
            ctaWhatsapp: 'Chat on WhatsApp',
            trustLine: 'Licensed service · Free cancellation up to 48h · Bilingual guides',
        },
        quote: {
            text1: '"The Douro is not a landscape,',
            text2: 'it is a geological poem."',
            author: 'Miguel Torga',
        },
        tourDouro: {
            badge: 'Most Booked',
            title: 'Douro Tour — Full-Day Experience',
            subtitle: 'Wine Tasting, Regional Lunch and River Cruise',
            intro: 'Discover the heart of the Douro Valley, a UNESCO World Heritage Site. Explore one of the oldest wine regions in the world in an experience carefully planned to offer comfort, authenticity and unforgettable moments.',
            timelineTitle: 'Your Day, Hour by Hour',
            timeline: [
                { time: '08:30', title: 'Pick-up in Porto', desc: 'The experience begins with pick-up in Porto. During the journey to the Douro, the guide shares insights about the region\'s history.' },
                { time: '10:00', title: 'Arrival at the Douro Valley', desc: 'First panoramic stops at the terraced vineyards. Photos at iconic viewpoints overlooking the river.' },
                { time: '10:30', title: 'Winery Visit', desc: 'Guided tour of a traditional producing estate. Tasting of DOC Douro and Port wines.' },
                { time: '12:30', title: 'Regional Lunch', desc: 'Traditional lunch at a selected restaurant, featuring regional dishes paired with local wines.' },
                { time: '14:30', title: 'River Cruise on the Douro', desc: 'Traditional boat cruise along the Douro River. Cinematic terraced landscapes.' },
                { time: '16:00', title: 'Return to Porto', desc: 'By late afternoon, we return to Porto with total comfort.' },
            ],
            includedTitle: 'What\'s Included',
            included: [
                'Round-trip transfer from Porto',
                'Visit to a selected winery',
                'DOC Douro wine tasting',
                'Traditional lunch paired with local wines',
                'Traditional boat cruise on the Douro',
                'Bilingual guide (Portuguese and English)',
            ],
            groupNote: 'Designed for small groups, ensuring personalised attention.',
            detailsTitle: 'Practical Info',
            duration: '8 to 9 hours (full day)',
            departure: 'Between 08:00 and 09:00 (confirmed on booking)',
            groupType: 'Private or shared (subject to availability)',
            languages: 'Portuguese and English',
            cancellation: 'Free cancellation up to 48 hours before the tour',
            forWhomTitle: 'Ideal For',
            forWhom: ['Couples', 'Groups of friends', 'Families', 'International visitors', 'Wine lovers'],
            price: '89',
            priceLabel: 'From',
            priceUnit: '€/person',
            priceIncludes: 'Transport + Winery + Wine + Cruise + Lunch',
            ctaBook: 'Book Your Experience',
            ctaWhatsapp: 'Questions? Talk to Us',
        },
        douroADois: {
            badge: 'Exclusive for Couples',
            title: 'Douro for Two — Exclusive Romantic Experience',
            subtitle: 'A Day Created Just for Two in the Douro Valley',
            intro: 'In the timeless setting of the Douro Valley, this experience has been designed for couples seeking exclusivity, privacy and truly memorable moments. Every step is planned as part of a romantic narrative.',
            noGroup: 'No groups. No rush. No distractions. Just the two of you, with the Douro as your backdrop.',
            timelineTitle: 'The Experience',
            timeline: [
                { time: '09:00', title: 'Private Pick-up in Porto', desc: 'Travel in a premium executive vehicle. The start of a day planned to the last detail.' },
                { time: '10:30', title: 'Panoramic Viewpoints', desc: 'Strategic stops at the most photogenic viewpoints in the Douro.' },
                { time: '11:00', title: 'Private Winery with Premium Tasting', desc: 'Private visit to a selected estate with premium wine tasting.' },
                { time: '13:00', title: 'Michelin Restaurant Lunch', desc: 'Reserved table at a Michelin-recognised restaurant.' },
                { time: '15:00', title: 'Decorated Private Boat', desc: 'Private boat cruise, specially decorated for the couple.' },
                { time: '17:00', title: 'Return to Porto', desc: 'A peaceful return journey, with memories to last a lifetime.' },
            ],
            boatTitle: 'The River Moment – Decorated Boat',
            boatDesc: 'The boat ride is not just a journey. The space is prepared with special décor for the couple, creating an intimate and sophisticated atmosphere. A perfect setting for marriage proposals, anniversaries, honeymoons or special dates.',
            photoTitle: 'Optional Service – Professional Photographer',
            photoDesc: 'For those who wish to immortalise the moment, we offer a professional photographer specialising in couples. Includes discreet coverage, sessions at iconic locations, professional selection and editing, with high-resolution digital delivery. (Available as an additional upgrade).',
            includedTitle: 'What\'s Included',
            included: [
                'Private executive transport (round-trip)',
                'Personalised experience planning',
                'Reservation at a Michelin-recognised restaurant',
                'Premium winery visit and tasting',
                'Private boat cruise with special decoration',
                'Personalised assistance (English/Portuguese)',
            ],
            price: '490',
            priceLabel: 'From',
            priceUnit: '€/couple',
            photoUpgrade: 'Photography service available as an additional option.',
            bookingNote: 'Early booking is recommended. The experience is subject to the availability of the restaurant and private boat.',
            ctaBook: 'Request Availability',
        },
        ctaWhatsapp: 'Plan Your Experience',
    },
    transfer: {
        badge: 'Premium Service',
        title: 'Executive Transfer in Porto',
        subtitle: 'Comfort, Punctuality and Excellence in Every Detail',
        intro: 'We offer a private executive transfer service in Porto, with pick-up and drop-off at your hotel, residence or Francisco Sá Carneiro Airport. A service designed for demanding travellers.',
        features: [
            { title: 'Punctuality and Premium Planning', items: ['Your time is valuable.', 'Real-time flight monitoring', 'Driver on location before scheduled time', 'Arrival waiting time included'] },
            { title: 'Executive Vehicle up to 8 Passengers', items: ['Comfortable, silent and spacious interior', 'Ample luggage space', 'Air conditioning', 'Ideal for families or corporate events'] },
            { title: 'Safety and Excellence', items: ['Experienced bilingual drivers', 'Baby seat (available upon request)', 'Fully licensed and insured service'] },
        ],
        services: [
            { title: 'Transfer Airport → Hotel', desc: 'Flight tracking, personalised reception at arrivals, total luggage assistance and direct transport to your destination.' },
            { title: 'Transfer Hotel → Airport', desc: 'Punctual pick-up at your hotel or accommodation with adequate planning to ensure a timely arrival at the airport.' },
        ],
        price: '45',
        priceLabel: 'From',
        priceUnit: '€/transfer',
        ctaBook: 'Request a Custom Quote',
        ctaWhatsapp: 'Book via WhatsApp',
    },
    about: {
        badge: 'About Us',
        title: 'Authentic Experiences in Northern Portugal',
        mission: 'At North Scape Tours, the client is not a tourist. They are a special guest.',
        pillars: [
            { title: 'The Douro you live', desc: 'Our itineraries go beyond the obvious. We connect each client to selected wineries, authentic gastronomic tastings and breathtaking landscapes.' },
            { title: 'Our differential', desc: 'Close, human and personalised service. Tailored itineraries and rigorous curation of local partners standing for excellence, comfort, and safety.' },
            { title: 'Far beyond the Douro', desc: 'We explore the historical heritage, gastronomy, and nature away from mass tourism, always with a high standard of service.' },
        ],
        promise: 'Our promise is to create memorable experiences, where every landscape, every wine and every moment becomes a real connection with Portugal.',
        teamTitle: 'The Team',
        teamDesc: 'Our team consists of professionals passionate about the Douro and Portuguese hospitality, always ready to welcome visitors from all over the world. We are ready to organise your experience.',
    },
    reviews: {
        badge: 'Reviews',
        title: 'What Our Guests Say',
        subtitle: 'Every review is a real story from someone who lived the experience.',
        rating: '4.9', totalReviews: '127',
        items: [
            { text: 'An experience that transcends tourism. We felt like guests of honour in one of the most beautiful regions in the world. The guide was exceptional and the attention to detail impressive.', author: 'Sofia Albuquerque', location: 'Lisbon, Portugal', flag: '🇵🇹', stars: 5 },
            { text: 'The attention to detail was impeccable. From the private boat ride to the exclusive wine tastings, everything was perfect. Highly recommended for anyone visiting Porto.', author: 'James Sterling', location: 'London, UK', flag: '🇬🇧', stars: 5 },
            { text: 'A magical day in the Douro Valley. The guide was exceptional, the wines superb and the lunch absolutely delicious. A must-do experience!', author: 'Marie Dubois', location: 'Paris, France', flag: '🇫🇷', stars: 4.5 },
            { text: 'Best experience ever in the Douro! The sunset boat ride was unforgettable. Highly recommend North Scape Tours.', author: 'Carlos Mendes', location: 'São Paulo, Brazil', flag: '🇧🇷', stars: 5 },
            { text: 'A perfect day in the Douro Valley! The wine tasting was first-class and the landscape breathtaking. We will definitely come back.', author: 'Hannah Müller', location: 'Munich, Germany', flag: '🇩🇪', stars: 4.8 },
            { text: 'We celebrated our anniversary with North Scape and it was the highlight of our trip. The private experience felt truly exclusive. Worth every penny.', author: 'Michael & Sarah Chen', location: 'New York, USA', flag: '🇺🇸', stars: 5 },
            { text: 'The guide knew everything about the wines and history of the region. An unforgettable journey I recommend to all wine lovers.', author: 'Alessandro Rossi', location: 'Milan, Italy', flag: '🇮🇹', stars: 4.5 },
            { text: 'The airport transfer was flawless, and the tour the next day exceeded all our expectations. First-class service throughout.', author: 'Lucía Fernández', location: 'Madrid, Spain', flag: '🇪🇸', stars: 5 },
            { text: 'Amazing experience! The boat on the Douro at sunset was magical. Professional service from start to finish.', author: 'Daan van der Berg', location: 'Amsterdam, Netherlands', flag: '🇳🇱', stars: 4.8 },
        ],
    },
    faq: {
        badge: 'FAQ',
        title: 'Everything You Need to Know',
        items: [
            { q: 'What\'s included in the Douro Tour?', a: 'The tour includes round-trip transfer from Porto, visit to a selected winery, DOC Douro wine tasting, lunch at a regional restaurant and a boat cruise on the Douro River. Bilingual guide (PT/EN) included.' },
            { q: 'How long does the experience last?', a: 'The Douro Tour is a full-day experience lasting 8 to 9 hours. The Douro for Two experience has the same duration.' },
            { q: 'Is it suitable for families with children?', a: 'Yes! The Douro Tour is ideal for families. Children are welcome and we have baby seats available for transfers. Children\'s menu options are available at restaurants.' },
            { q: 'Can I customise the experience?', a: 'Absolutely. We offer private tours where you can adapt the itinerary, choose specific wineries or add extra stops. Contact us for a bespoke tour.' },
            { q: 'What is the cancellation policy?', a: 'Free cancellation up to 48 hours before the tour date. After this deadline, the full rate applies.' },
            { q: 'Are there vegetarian options or dietary accommodations?', a: 'Yes. Our partner restaurants offer vegetarian, vegan and allergy-adapted options. Please inform us at the time of booking.' },
            { q: 'Do tours operate year-round?', a: 'Yes, tours run throughout the year. Each season offers a different landscape: green vines in spring, harvest in autumn and golden terraces in winter.' },
            { q: 'How does the executive transfer work?', a: 'The driver arrives before the scheduled time. For airport transfers, we monitor your flight in real time. Executive vehicle with capacity for up to 8 passengers.' },
            { q: 'What languages are tours available in?', a: 'Our guides are fluent in Portuguese and English. For other languages, please contact us to check availability.' },
            { q: 'How can I book?', a: 'You can book directly through our website, via WhatsApp or by email. We confirm your booking within 2 hours.' },
        ],
    },
    blog: {
        badge: 'Blog',
        title: 'Stories from the Douro',
        subtitle: 'Tips, itineraries and inspiration for your trip.',
        readMore: 'Read Article',
        items: [
            {
                slug: 'miradouros-douro', title: 'The 5 Most Instagrammable Viewpoints in the Douro Valley', excerpt: 'From the legendary São Leonardo de Galafura to the artistic Miradouro do Imaginário — the viewpoints that turn every photo into a masterpiece. Discover the region\'s best-kept secrets.', date: '18 Feb 2026', category: 'Viewpoints', image: '/images/blog/douro_viewpoint_1771611805242.png', readTime: '5 min',
                fullContent: [
                    { type: 'p', text: 'The Douro Valley is not merely seen; it is lived. It is one of those rare places on Earth where human intervention — the imposing schist terraces carved by hand over centuries — has not destroyed nature, but rather elevated it to sublime art. However, to capture the true essence of this World Heritage region, simply being here isn\'t enough. You must know exactly where to look.' },
                    { type: 'p', text: 'Prepare your camera, clean your lens, and join us on this journey through the 5 most spectacular, dramatic, and perfectly photogenic viewpoints in the Viseu and Vila Real districts. These are not just stops; they are invitations to absolute wonder.' },
                    { type: 'h3', text: '1. São Leonardo da Galafura Viewpoint' },
                    { type: 'p', text: 'At 640 meters high, the air is thinner, but the reward will take away your remaining breath. Miguel Torga, the illustrious Portuguese poet, immortalised this location by calling it an "excess of nature". At sunrise, the blanket of fog over the river creates an almost mystical setting; by late afternoon, the valley ignites in an ethereal golden hue.' },
                    { type: 'image', url: '/images/blog/douro_viewpoint_1771611805242.png', text: 'The breathtaking view from São Leonardo da Galafura. Pro tip: bring a wide-angle lens after 5 PM to capture the golden spectacle across the vines.' },
                    { type: 'p', text: '📍 Coordinates: 41.1738° N, 7.6710° W. \n💡 Magic Tip: Bring a glass of your favourite Tawny and make a silent toast to the river\'s magnitude.' },
                    { type: 'h3', text: '2. Casal de Loivos Viewpoint' },
                    { type: 'p', text: 'The BBC named it owner of one of the six best views in the world, and for good reason. It is from here that the Douro gains its famous perfect elbow-shaped curve, just past the village of Pinhão. This is the image that graces Portugal\'s most beautiful postcards and international luxury travel magazines.' },
                    { type: 'blockquote', text: 'At Casal de Loivos, we realise our human smallness in the face of the millennial persistence of a river that carved its own destiny.' },
                    { type: 'h3', text: '3. Imaginário Viewpoint (Tabuaço)' },
                    { type: 'p', text: 'While most tourist buses crowd the north bank, the south bank hides this sparkling secret. It offers a dramatic, clean, and almost palpable view over the staircase vineyards. If you seek the "clean" photograph, without distractions and without having to ask strangers to step out of the frame, this is your refuge.' },
                    { type: 'h3', text: '4. São Salvador do Mundo Viewpoint' },
                    { type: 'p', text: 'In the municipality of São João da Pesqueira, this complex of white chapels contrasts gloriously with the rawness of the rocky escarpment landscape that strangles the river. The dizzying height allows you to frame the river far below, snaking through wild gorges that recall the untouched genesis of the region.' },
                    { type: 'h3', text: 'Our Guides\' Secret' },
                    { type: 'p', text: 'Discovering these spots in your own car means navigating winding, steep roads that are often unnerving for those unfamiliar with the region\'s unique geography. By booking a private experience with North Scape Tours, our expert chauffeurs not only guarantee a safe journey in a premium vehicle but also know the exact curve and the perfect golden hour light to park and let you capture the photograph of a lifetime.' }
                ]
            },
            {
                slug: 'vinhos-douro-antigo-novo', title: 'Old Douro vs. New Douro: The Wine Guide You Need to Taste', excerpt: 'From the imposing Vintage Port to the new generation of acclaimed unfortified white and red wines. Discover the evolution that placed the Douro on the map of haute cuisine.', date: '12 Feb 2026', category: 'Wines', image: '/images/blog/douro_wine_1771611833006.png', readTime: '6 min',
                fullContent: [
                    { type: 'p', text: 'For over three hundred years, the name "Douro" was unequivocally synonymous with a single nectar: the imposing, sweet, and fortified Port Wine. Served in the majestic halls of London, in the dusty cellars of ancient bishops, and in the celebratory toasts of royalty, Port dictated the rules.' },
                    { type: 'p', text: 'Today, however, the region faces a breathtaking duality. Side by side with the classic Tawnies and secular Vintages now rest table wines (DOC Douro) that compete shoulder to shoulder with the giants of Bordeaux and Burgundy. But what does this mean, in practice, for your palate?' },
                    { type: 'h3', text: 'The Timeless Ritual of Port' },
                    { type: 'p', text: 'Tradition still rules majestically in the grand, silent Quintas. The classic Douro method refuses to surrender to machines where humans prove to be irreplaceable: foot treading.' },
                    { type: 'image', url: '/images/blog/douro_wine_1771611833006.png', text: 'Treading in granite lagares is not a tourist attraction; it is artisanal science. The human foot extracts colour and flavour without crushing the grape seed, preventing bitterness.' },
                    { type: 'p', text: 'In a Vintage — the royalty of Ports —, the grapes are carefully chosen, undergo short maceration, and age in the bottle for decades. A Vintage Port from an exceptional year is not just wine; it is a time capsule, dark, dense, exuberant in notes of black plum, chocolate, and wild spices.' },
                    { type: 'h3', text: 'The DOC Douro Revolution: The "New Douro"' },
                    { type: 'p', text: 'If the past was fortified, the present is surprisingly elegant. In the late 90s, a group of visionary producers (often called the "Douro Boys") began to show the world that, if we stopped early fortification, the hot and harsh schist terroir generated mineral, sharp, and deeply gastronomic white wines, and reds of enormous complexity and freshness.' },
                    { type: 'blockquote', text: 'The fascinating paradox of the modern Douro is how such harsh lands produce wines so unusually elegant. It is the triumph of the vine over the stone.' },
                    { type: 'h3', text: 'A Quick Tasting Guide' },
                    { type: 'p', text: 'When you sit at a Quinta table with us, seek out the traits of the 5 great native Douro grapes:' },
                    { type: 'p', text: '🍷 **Touriga Nacional:** The sublime perfume. Look for unmistakable aromas of violets, bergamot (like Earl Grey tea), and blackberries.' },
                    { type: 'p', text: '🍷 **Touriga Franca:** The structure, which brings light floral aromatic body but ensures the wine lingers perfectly on the palate.' },
                    { type: 'p', text: '🍷 **Tinta Roriz:** Known globally as Tempranillo, it brings pepper, rockrose, and crisp red fruits.' },
                    { type: 'p', text: 'In our exclusive tasting experiences, we reserve for you not just the tastings, but meetings in private spaces or even direct barrel tastings in estates that refuse ordinary guests. An enological journey for life.' }
                ]
            },
            {
                slug: '3-dias-douro-comboio', title: '3 Days in the Douro Without a Car: The Complete Train Itinerary', excerpt: 'Forget parking worries and alcohol limits. The Porto–Pinhão train ride is one of the most beautiful railway journeys in Europe.', date: '6 Feb 2026', category: 'Itineraries', image: '/images/blog/douro_train_1771611847706.png', readTime: '5 min',
                fullContent: [
                    { type: 'p', text: 'Imagine boarding a train in the bustling centre of Porto and, an hour later, seeing the river water almost touching the carriages through your window. The Douro railway line hugs the river escarpments with formidable intimacy. For much of the way, there is no accompanying road: just the train, the mirrored water, and, in the background, the green staircases rising to the heavens.' },
                    { type: 'p', text: 'If your goal is to push stress away and focus on premium wine tasting without the fear of driving, building your trip 100% by train is the best tourism decision you could make.' },
                    { type: 'h3', text: 'Day 1: Immersive Arrival in Pinhão' },
                    { type: 'p', text: 'Catch the morning train at the stunning São Bento station in Porto. We advise always sitting on the RIGHT SIDE (in the Porto-Régua-Pinhão direction) to guarantee front-row river views. The arrival at Pinhão station is postcard-worthy: it is decorated with over twenty-four tile panels illustrating the golden eras of the harvests.' },
                    { type: 'image', url: '/images/blog/douro_train_1771611847706.png', text: 'Pinhão train station: the walls tell the history of the famous rabelo boat journeys to Porto.' },
                    { type: 'h3', text: 'Day 2: Accessibility on Foot (Boat and Wines)' },
                    { type: 'p', text: 'Pinhão concentrates immense wealth within a two-kilometre radius. In the morning, take advantage of the picturesque river pier to board a vintage cruise. The river offers total calm and silence. In the afternoon, know that you don\'t need a car to visit big names: renowned estates like Quinta das Carvalhas or Quinta do Bomfim are a five or ten-minute walk from the village centre.' },
                    { type: 'h3', text: 'Day 3: The Flexible Luxury Option' },
                    { type: 'p', text: 'A train-only plan has one flaw: altitude limits. The highest, most remote estates and the grand viewpoints are hopelessly out of walking range. This is where the secret of luxury travel comes in.' },
                    { type: 'blockquote', text: 'The ultimate experience is taking the train solely for the scenic visual charm, and having a private chauffeur await your arrival at the stations.' },
                    { type: 'p', text: 'For North Scape Tours clients, we coordinate our Premium Vehicle so the couple can take the beautiful train routes and be collected directly at Pinhão station by their chauffeur/guide. We drive through the mountains to the Michelin-starred restaurant and the private high-altitude tastings they would otherwise miss, before returning them to the station at sunset. The absolute combination of the picturesque with supreme luxury.' }
                ]
            },
            {
                slug: 'vindima-douro-experiencia', title: 'The Magic of the Harvest: The Sensory Experience That Changes the Soul', excerpt: 'Treading grapes in centuries-old stone lagares to the sound of rhythmic chants. Autumn in the Douro is a visceral communion between man, stone, and sun.', date: '30 Jan 2026', category: 'Experiences', image: '/images/blog/douro_harvest_1771611862889.png', readTime: '5 min',
                fullContent: [
                    { type: 'p', text: 'Forget red carpets; true European privilege is walking barefoot, with purple grape must up to your mid-ankle, in a granite stone lagar in a steep valley in Portugal. September and October transform the calm valley into a contagious organic frenzy; it is the time when the region reclaims an entire secular heritage and fulfils the goal of a whole year of intense dedication.' },
                    { type: 'h3', text: 'The Lagar Choreography (Cutting and Treading)' },
                    { type: 'p', text: 'The experience at the Quintas during harvest time allows you to go far beyond the traditional tourist photograph. After sharing lunch and the morning chores on the steep slopes (cutting thick bunches from ancient vines on suspended platforms under the sun), twilight arrives. The focus shifts.' },
                    { type: 'image', url: '/images/blog/douro_harvest_1771611862889.png', text: 'The dizzying incline of the vines and the proximity of the river perfectly demonstrate the title of "heroic viticulture".' },
                    { type: 'p', text: 'Legs are carefully washed, trousers rolled up. Men and women form a line arm in arm inside the centuries-old stone reservoirs — the lagar. A synchronised cadence then begins: "One... Two... Left... Right...".' },
                    { type: 'p', text: 'This movement — once exhausting and monotonous for the ancestors who spent nights and early mornings there — ensures the grape must is crushed, extracting intensified colour and flavour from the skin, without crushing the delicate seeds whose bitterness would ruin rare batches.' },
                    { type: 'blockquote', text: 'Diving into a Douro stone lagar under a starry sky is to absorb the potent smells of crushed fruit and vibrant human heat — there is no spa in the world with the energy of this tradition.' },
                    { type: 'h3', text: 'Strategic Planning for 2026' },
                    { type: 'p', text: 'Participating in a real harvest is not a ticket you can buy at a counter. Spots at the best estates sell out six to eight months in advance. At North Scape Tours, we achieve the impossible through our deep and rooted network of regional contacts: we open doors at estates reserved only for exclusive guests.' },
                    { type: 'p', text: 'Let us be the choreographers of your immersion. We have prepared harvest journeys for those seeking luxury and raw essence in the perfect middle ground. Speak with us for September agenda planning — it will be worth its weight in gold.' }
                ]
            },
        ],
    },
    contact: {
        title: 'Ready to embark?',
        desc: 'Let us design your dream trip. We reply within 2 hours.',
        ctaBook: 'Book Experience', ctaWhatsapp: 'Chat on WhatsApp',
        emailLabel: 'Email', email: EMAIL,
        phoneLabel: 'Phone', phone: '+351 911 923 499',
    },
    footer: {
        rights: 'All rights reserved.',
        terms: 'Terms and Conditions', privacy: 'Privacy Policy',
        licensedIn: 'Licensed service in Portugal · RNAVT No. 11959',
        nif: 'VAT Number: 247 114 430',
        complaints: 'Electronic Complaints Book'
    },
    cookieBanner: {
        text: 'We use cookies to ensure you get the best experience on our website. By continuing, you agree to our',
        linkText: 'Privacy Policy',
        acceptBtn: 'Accept All',
        essentialBtn: 'Essentials Only',
    },
    mobileBar: { book: 'Book Now', whatsapp: 'WhatsApp' },
};
